### ISSUE TITLE
Unable to compile mrpt_ros or 

### ISSUE THREAD

**Issue by ARGaditya** [MRPT/mrpt_ros#2]
I am not sure if this is the correct repository to ask this question, but I am having a hard time following the documentation to get mrpt working in ROS1 (noetic).
This is usually the way that is install it -> `sudo apt install ros-noetic-pose-cov-ops`
But after I updated my packages, I am seeing missing library errors especially from `ros1bridge` module.

After some searching, I found this [link](https://github.com/MRPT/mrpt#34-as-a-ros-package), but although I am able to install mrpt2, I still am facing the missing library issues.

More digging led me to [this](https://github.com/MRPT/mrpt_ros#motivation-for-the-change) , where I learned that mrpt2 is obsolete.

After referring to the changelog on your website I found this [change](https://docs.mrpt.org/reference/latest/page_changelog.html#version-2-13-6-released-aug-14th-2024). 

Upon seeing the ROS build farm status as [green](https://github.com/MRPT/mrpt_ros?tab=readme-ov-file#build-status-matrix) for all ROS 1 noetic packages, I tried to install using `sudo apt install ros-${ROS_DISTRO}-mrpt_libposes` , but apt could not find it.

Then when I try to build the repo from source I am facing this issue as highlighted below:

```
In file included from /home/xxxxxxxx/mrpt_ws/build_isolated/mrpt_libmath/devel/mrpt-build/src/mrpt/libs/math/src/CSparseMatrix.cpp:12:
In file included from /home/xxxxxxxx/mrpt_ws/build_isolated/mrpt_libmath/devel/mrpt-build/src/mrpt/libs/math/include/mrpt/math/CSparseMatrix.h:23:
/usr/include/suitesparse/cs.h:442:14: error: 'cs_ci_house' has C-linkage specified, but returns user-defined type 'cs_complex_t' (aka 'complex<double>') which is incompatible with C [-Werror,-Wreturn-type-c-linkage]
  442 | cs_complex_t cs_ci_house (cs_complex_t *x, double *beta, int n) ;
      |              ^
/usr/include/suitesparse/cs.h:582:14: error: 'cs_cl_house' has C-linkage specified, but returns user-defined type 'cs_complex_t' (aka 'complex<double>') which is incompatible with C [-Werror,-Wreturn-type-c-linkage]
  582 | cs_complex_t cs_cl_house (cs_complex_t *x, double *beta, cs_long_t n) ;
```

```
<== Failed to process package 'mrpt_libmath': 
  Command '['/home/xxxxxxxx/mrpt_ws/devel_isolated/mrpt_libbase/env.sh', 'make', '-j32', '-l32']' returned non-zero exit status 2.

Reproduce this error by running:
==> cd /home/xxxxxxxxx/mrpt_ws/build_isolated/mrpt_libmath && /home/amulampally/mrpt_ws/devel_isolated/mrpt_libbase/env.sh make -j32 -l32
```

Please guide me on how to resolve this issue. If you need any more information please let me know.
System Info:
```
OS: 20.04.1-Ubuntu
kernel version: 5.15.0-122-generic
ROS Version : ROS1 Noetic
gcc version : 13.1.0
```

PS: we just use the compose and inverseCompose functions that are used as shown [here](https://wiki.ros.org/pose_cov_ops)

**Comment by jlblancoc** [comment]
You might have fallen into a problematic situation because of the transition from `mrpt2` to `mrpt_lib*`?

Try first to remove all MRPT apt packages: 

    sudo apt remove ros*mrpt

In particular, make sure of removing the now deprecated `mrpt2` package, from apt, and from your local workspace. 

Then, after that, just installing `sudo apt install ros-noetic-pose-cov-ops` should work (I tested it on a clean docker image and it works). Or, if I didn't got your point and what fails is your program that **uses** pose-cov-ops, please, confirm it so we can debug it.

PS: `sudo apt install ros-${ROS_DISTRO}-mrpt_libposes` should be `sudo apt install ros-${ROS_DISTRO}-mrpt-libposes`. For Debian/Ubuntu packages, underscores are replaced by `-` for all ROS packages.

**Comment by jlblancoc** [comment]
@ARGaditya 

I just fixed a missing exported cmake symbol for ROS1 packages in pose_cov_ops (https://github.com/mrpt-ros-pkg/pose_cov_ops/commit/29786320d480ba9c6ecf1d273b4bcf47b7a29617), and created this example package as reference: 

    https://github.com/mrpt-ros-pkg/pose_cov_ops_example_ros1_package

I'll make another release for pose_cov_ops for Noetic with the fix, but it will take weeks to get installable via "apt", so in the meanwhile you can get the latest `pose_cov_ops` and build it from sources.

**Comment by ARGaditya** [comment]
Thank you for getting back to me with a fix. I am away from my work machine now, I will try it as soon as I am in front of it.

**Comment by ARGaditya** [comment]
> @ARGaditya
> 
> I just fixed a missing exported cmake symbol for ROS1 packages in pose_cov_ops ([mrpt-ros-pkg/pose_cov_ops@2978632](https://github.com/mrpt-ros-pkg/pose_cov_ops/commit/29786320d480ba9c6ecf1d273b4bcf47b7a29617)), and created this example package as reference:
> 
> ```
> https://github.com/mrpt-ros-pkg/pose_cov_ops_example_ros1_package
> ```
> 
> I'll make another release for pose_cov_ops for Noetic with the fix, but it will take weeks to get installable via "apt", so in the meanwhile you can get the latest `pose_cov_ops` and build it from sources.

Thank you for the examples and the fix. This seemed to have fixed it. 
I had to install `ros-noetic-mrpt-libros-bridge` as a dependent first and then compile it from source. 
Is there any way to know if your changes have made it to the apt repos?

**Comment by jlblancoc** [comment]
Good!

Yes, there are two ways: 
- Keep an eye on the "Stable release" badges (right column) in [this table](https://github.com/mrpt-ros-pkg/pose_cov_ops), and when 0.3.13 is shown, it means doing an "apt update && apt upgrade" will get the latest version; 
- Or, watch the ROS discourse release and packaging page, where they announce "sync"s, as releases are named.

Cheers,
